# Changed publish directory for Github Pages
publishDir = "docs"

baseURL = "https://posts.dwhacademy.com/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "DWH Academy Posts: Agile Data warehousing in the practise"
theme = "cayman-hugo-theme"

# Google analytics
googleAnalytics = "UA-143050521-1"

# Disqus comments
disqusShortname = "dwh-academy-posts"

# Syntax highlighting
pygmentsCodefences = true
pygmentsStyle = "pygments"

[taxonomies]
  author = "authors"
  tag = "tags"
  category = "categories"

[permalinks]
  post = "/:filename/"

[params]
  # Header text, can be markdown
  project_name = "DWH Academy Posts"
  project_tagline = "Agile Data warehousing in the practise"

  # Date format for post list and single pages
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat = "2006-01-02"

  # Footer text, can be markdown
  footer = "Made with [Hugo](https://gohugo.io/). Themed by [Cayman](https://github.com/zwbetz-gh/cayman-hugo-theme). <br/>Deployed to [GitHub](https://github.com/).<br/><br/>&copy; DWH Academy 2019"

  # If true, the CSS/JS for Katex math typesetting are enabled
  katex = true

  # Breakpoints
  large_breakpoint = "64em"
  medium_breakpoint = "42em"

  # Header colors
  header_heading_color = "#fff"
  header_background_color = "#159957"
  header_background_color_secondary = "#155799"

  # Text colors
  section_headings_color = "#159957"
  body_text_color = "#606c71"
  body_link_color = "#1e6bb8"
  blockquote_text_color = "#819198"

  # Code colors
  code_background_color = "#f3f6fa"
  code_text_color = "#567482"

  # Border colors
  border_color = "#dce6f0"
  table_border_color = "#e9ebec"
  hr_border_color = "#eff0f1"

[menu]

  [[menu.nav]]
    name = "Latest Posts"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "Main topics"
    url = "/categories/"
    weight = 2
  [[menu.nav]]
    name = "Tags"
    url = "/tags/"
    weight = 3
  [[menu.nav]]
    name = "Authors"
    url = "/authors/"
    weight = 4
  [[menu.nav]]
    name = "DWH Academy"
    url = "https://dwhacademy.com/"
    weight = 5


